---
- name: Get list of installed plugins.
  command: >
    ./bin/logstash-plugin list
    chdir={{logstash_install_dir}}
  register: logstash_plugins_list
  changed_when: false

- name: Install configured plugins.
  command: >
    ./bin/logstash-plugin install {{ item }}
    chdir={{logstash_install_dir}}
  with_items: "{{ logstash_install_plugins }}"
  when: "item not in logstash_plugins_list.stdout"
  notify: restart logstash
  environment:
    JAVA_OPTS: "{%if http_proxy is defined %}-Dhttp.proxyHost={{ http_proxy.split(':')[0:1].join(':') }} -Dhttp.proxyPort={{ http_proxy.split(':')[2] }} {%endif%}"
